apiVersion: v1
kind: Service	
metadata:
  name: nodeport-service
  labels:
    app: test-nodeport
spec:
  selector:
    app: app1
  type: NodePort
  ports:
  - nodePort: 31111
    port: 8080
    targetPort: 8080
