apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator
spec:
  selector:
    matchLabels:
      app: validator
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: validator
    spec:
      containers:
      - name: validator
        image: docker.io/bhartim15/validmongodb
        ports:
        - containerPort: 8080
        env:
            - name: MONGO_URI
              value: mongodb
